image: Ubuntu1804 # образ для сборки
stack: node 10 # окружение
branches:
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - yarn # команда установки зависимостей
build: off
build_script:
  - yarn build # команда сборки
test_script:
  - yarn lint && yarn run test --passWithNoTests # скрипт тестирования

